PROJECT_FOLDER=$1
ACCESSIBLE_FOLDERS="$PROJECT_FOLDER/resources,$PROJECT_FOLDER/mods"

deno run --allow-read="$ACCESSIBLE_FOLDERS,." --allow-write="$ACCESSIBLE_FOLDERS" index.ts $PROJECT_FOLDER $2 $3
